import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { isDraftMode } from "@/lib/locale";
import DraftModeBar from "@/atoms/layout/DraftModeBar";
import LiveVisualEditing from "@/wrappers/presentation/VisualEditing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const draft = await isDraftMode();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {draft && <DraftModeBar />}
        {children}
      </body>
      {draft && <LiveVisualEditing />}
    </html>
  );
}
