import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dovre_social = localFont({ 
  src: "./fonts/DovreSocial-Light.woff2",
  variable: "--font-dovre-social",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${dovre_social.variable}`}>
      {children}
    </html>
  );
}
